//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiForExamMobile.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseForExamMobileEntities : DbContext
    {
        public BaseForExamMobileEntities()
            : base("name=BaseForExamMobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BuildingMaterials> BuildingMaterials { get; set; }
        public virtual DbSet<HatShop> HatShop { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TableGames> TableGames { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WaxFigures> WaxFigures { get; set; }
    }
}
