//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiForExamMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> StockAvailability { get; set; }
        public Nullable<int> AvailabilityInTheStore { get; set; }
        public string Description { get; set; }
        public string Rewiews { get; set; }
        public string Image { get; set; }
    }
}
